### ISSUE TITLE
`libssl.so.1.1` is a non-obvious dependency for Kerblam!

### ISSUE THREAD

**Issue by Feat-FeAR** [MrHedmad/kerblam#42]
Running any kerblam module on my [ManjaroWSL2](https://github.com/sileshn/ManjaroWSL2) returned the following error message:

`kerblam: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

However, upon `sudo pacman -Syu openssl-1.1` everything worked fine.

From the [official Manjaro forum](https://forum.manjaro.org/t/missing-libssl-how-do-i-install-it/129872/2) I found that:
_openssl is a dependency for a lot of system packages, so I find it hard to believe you don’t have it installed. What you might actually be missing is openssl-1.1, which is no longer a requirement for most stuff, but some stuff has not been updated/rebuilt for ssl 3.0 yet, so it will complain if you don’t have the openssl-1.1 package installed._

Consider to explicitly add `openssl-1.1` as a Kerblam! dependency inside the documentation, or move to ssl 3.0.

**Comment by MrHedmad** [comment]
I'm aware of this. I also had the same problem just the other day on my Arch machine.
I was looking into it, but as far as I can tell some of my dependencies pull in the requirement, and I'm not sure which or why it would pull such an old `libssl`.

I will try to bulk-update the libraries used by kerblam! and we can see whether that fixes it. Sorry for the inconvenience.

**Comment by MrHedmad** [comment]
The `openssl` dependency was dropped, so this is fixed! Thanks for pointing it out Fede <3
